version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
     - ./app/sources:/usr/src/app
    command: sh -c "cd ${REACT_PROJECT_NAME} && yarn start"
    ports:
     - "3000:3000"
    tty: true
    stdin_open: true